In [1]:
import os
import rootpath
import sys
sys.path.append(rootpath.detect())

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib qt
import json

from testsuite.results import ResultsContainer

In [2]:
def load_file(file_name):
    return ResultsContainer(os.path.join(processed_results_dir, file_name))

In [3]:
processed_results_dir = "../processed_results"
processed_files = list(sorted(os.listdir(processed_results_dir)))
print(len(processed_files))

100


In [4]:
problems = set([p.split("__")[0] for p in processed_files])

In [5]:
# for i in [19, 37, 55]:
for i in [57]:
    a = load_file(processed_files[i])
    # fig01 = a.plot_hpv()
    # a.plot_hpv(reference=True, axis=fig01.gca(), c="C3")
    
    fig02 = a.plot_igd()
    a.plot_igd(reference=True, axis=fig02.gca(), c="C3")
    print(f"WFG{a.n_prob[0]} {a.n_obj[0]}obj {a.n_dim[0]}dim")
    
    fig1 = plt.figure(figsize=[8,8])
#     ax1 = fig1.gca(projection="3d")
    ax1 = fig1.gca()
    for r0 in a.results:
        r0.plot_front(axis=ax1, c="C0")
    for r1 in a.reference:
        r1.plot_front(axis=ax1, c="C3")
    ax1.scatter(*np.asarray(r0.targets).T, c="magenta", s=20)
    ax1.set_xlim(0, ax1.get_xlim()[1])
    ax1.set_ylim(0, ax1.get_ylim()[1])

WFG4 2obj 6dim


In [42]:
r0.hpv_refpoint

array([2.66666667, 4.24153325])

In [43]:
r1.hpv_refpoint

array([2.66666667, 4.24153325])

In [44]:
r0.targets

array([[0.4, 3.2]])

In [45]:
r1.p.max(axis=0)

array([2.0286518 , 4.01262958])

In [ ]:
problem_instances = [57]